name: Test Workflow

on: [push]

jobs:
  run_control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "aws" {
              plugin     = "aws"
              access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
              secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              regions    = ["ap-south-1"]
            }

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Run
        run: |
          steampipe -v
          powerpipe -v
          steampipe service start

      - name: Run Control
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/turbot/steampipe-mod-aws-compliance"
          controls: |
            ebs_volume_unused
          pipes-snapshot-visibility: 'anyone_with_link'
          pipes-token: "${{ secrets.PIPES_TOKEN }}"

      - name: Stop
        run: |
          steampipe service stop --force

  run_benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "aws" {
              plugin     = "aws"
              access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
              secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              regions    = ["ap-south-1"]
            }

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Run
        run: |
          steampipe -v
          powerpipe -v
          steampipe service start

      - name: Run Benchmark
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/turbot/steampipe-mod-aws-compliance"
          benchmarks: |
            cis_v150
          pipes-snapshot-visibility: 'anyone_with_link'
          pipes-token: "${{ secrets.PIPES_TOKEN }}"

      - name: Stop
        run: |
          steampipe service stop --force

  run_duckdb_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Run
        run: |
          powerpipe -v

      - name: Run Control
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/pskrbasu/powerpipe-mod-duckdb-demo"
          controls: |
            testing_control
          pipes-snapshot-visibility: 'anyone_with_link'
          pipes-token: "tpt_cnnggphtvnqvvaebj9j0_p8j3x6ij79js4ny8po8r6vz5"
          database: "duckdb:///$(pwd)/test_data/employee.duckdb"
