name: Test Non-IaC Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "aws" {
              plugin     = "aws"
              access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
              secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              regions    = ["ap-south-1"]
            }

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Start Steampipe and Powerpipe
        run: |
          steampipe -v
          powerpipe -v
          steampipe service start

      - name: Run Control
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/turbot/steampipe-mod-aws-compliance"
          controls: |
            ebs_volume_unused
          pipes-snapshot-visibility: 'anyone_with_link'
          pipes-token: "${{ secrets.PIPES_TOKEN }}"

      - name: Stop
        run: |
          steampipe service stop

  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "aws" {
              plugin     = "aws"
              access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
              secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              regions    = ["ap-south-1"]
            }

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Start Steampipe and Powerpipe
        run: |
          steampipe -v
          powerpipe -v
          steampipe service start

      - name: Run Benchmark
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/turbot/steampipe-mod-aws-compliance"
          benchmarks: |
            cis_v150
          pipes-snapshot-visibility: 'anyone_with_link'
          pipes-token: "${{ secrets.PIPES_TOKEN }}"

      - name: Stop
        run: |
          steampipe service stop

  test-database-flag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Verify Powerpipe is installed
        run: |
          powerpipe -v

      - name: Run Control
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/pskrbasu/powerpipe-mod-duckdb-demo"
          controls: |
            testing_control
          pipes-snapshot-visibility: 'anyone_with_link'
          pipes-token: "${{ secrets.PIPES_TOKEN }}"
          database: "duckdb:///$(pwd)/test_data/employee.duckdb"
