# Run this workflow manually before Release to ensure that the IaC checks are passing.
name: Test IaC Checks

on:
  workflow_dispatch:

jobs:
  run-iac-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Steampipe
        uses: turbot/steampipe-action-setup@v1
        with:
          plugin-connections: |
            connection "aws_tf" {
              plugin = "terraform"
              configuration_file_paths = [ "./test_data/terraform/aws/**/*.tf" ]
            }

      - name: Install Powerpipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"

      - name: Start Steampipe and Powerpipe
        run: |
          steampipe -v
          powerpipe -v
          steampipe service start

      - name: Run Terraform checks
        uses: ./ # This points to your local action
        with:
          mod-url: "https://github.com/turbot/steampipe-mod-terraform-aws-compliance"
          controls: |
            ec2_instance_uses_imdsv2

      - name: Stop
        run: |
          steampipe service stop
